FROM centos
#npm
ADD node-v14.15.4-linux-x64.tar.xz /usr/local/lib/nodejs/
ENV PATH /usr/local/lib/nodejs/node-v14.15.4-linux-x64/bin:$PATH
#jdk
ADD jre-8u311-linux-x64.rpm jre-8u311-linux-x64.rpm
ADD apache-maven-3.6.3 /usr/local/lib/apache-maven-3.6.3
#COPY jre-8u311-linux-x64.rpm /duqian/
#WORKDIR /duqian
RUN rpm -ivh jre-8u311-linux-x64.rpm
#wget
RUN yum install -y wget
#dumb-init 一个 Docker 容器初始化系统
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_amd64.deb
RUN chmod +x /usr/local/bin/dumb-init

RUN yum install -y epel-release
RUN yum install -y git
RUN yum install -y net-tools
RUN yum install -y p7zip
 
ENV JAVA_HOME /usr/java/default
ENV PATH /usr/local/lib/apache-maven-3.6.3/bin:$PATH
ENV LANG en_US.UTF-8
ENV TZ=Asia/Shanghai

VOLUME /dq-coverage
ADD jacoco.web-1.0.0.jar jacoco-web.jar
ADD jacococli.jar jacococli.jar
ADD cmdShell.sh cmdShell.sh
#ADD dq-coverage dq-coverage
RUN chmod 775 jacococli.jar
RUN chmod +x cmdShell.sh
RUN chmod +x jacoco-web.jar
RUN chmod +x jacococli.jar

#RUN npm install http-server -g

# PORT
EXPOSE 8090

# 只能有一个入口，http-server和jar只能一个生效？
#CMD ["http-server"]
#CMD ["http-server","dq-coverage","-p","8082"]

# 运行jar包
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","jacoco-web.jar"]

#维护者
MAINTAINER duqian2010@gmail.com